#!/bin/bash

VERSION="1.8.1"

HERE=$(dirname "$0")
SCRIPT=$(readlink -f "$0")
PHP_HELPERS="php $HERE/helpers.php"

MEGA_API_URL="https://g.api.mega.co.nz"
OPENSSL_AES_CTR_128_DEC="openssl enc -d -aes-128-ctr"
OPENSSL_AES_CBC_128_DEC="openssl enc -a -A -d -aes-128-cbc"
OPENSSL_AES_CBC_256_DEC="openssl enc -a -A -d -aes-256-cbc"

for i in pv openssl wget php md5sum; do
	if [ "`which $i`" == "" ]; then
		showHelp
		showError "ERROR: Command $i is required and not installed"
	fi
done

function showHelp {
	echo -e "\nmegadown v$VERSION - https://github.com/tonikelope/megadown"
	echo -e "\nmega.co.nz and megacrypter download bash script"

	echo -e "\nUsage"
	echo -e "\t./megadown '[link]' [-o|--output new_file_name] [-s|--speed speed_limit_bytes_second] [-p|--password mc_url_pass]"
	echo -e "\t./megadown [-l|--list file_list] [-s|--speed speed_limit_bytes_second] [-p|--password mc_url_pass]"

	echo -e "\nParameters"
	echo -e "\t-l | --list                  get links from text file. To set new names to list files, add the new name after a space for each line."
	echo -e "\t-o | --output                store file with this name"
	echo -e "\t-s | --speed                 download speed limit (500b, 500k, 2m)"
	echo -e "\t-p | --password              password to protected files"

	echo ''
}

# 1:b64_encoded_String
function b64_pad {
	b64=$(echo -ne "$1" | tr '\-_' '+/')
	pad=$(((4-${#1}%4)%4))

	for i in $(seq 1 $pad); do
		b64="${b64}="
	done

	echo -n "$b64"
}

# 1:hex_raw_key
function hrk2hk {
	hk[0]=$(( 0x${1:0:16} ^ 0x${1:32:16} ))
	hk[1]=$(( 0x${1:16:16} ^ 0x${1:48:16} ))

	printf "%016x" ${hk[*]}
} 

function showError {
	echo -e "\n$1\n" 1>&2
	exit 1
}


function get_mc_link_info {
	
	MC_API_URL=$(echo -n "$1" | grep -i -E -o 'https?://[^/]+')"/api"
	
	wget_exit_code=1
	
	info_link=$(wget -q --header='Content-Type: application/json' --post-data "{\"m\":\"info\", \"link\":\"$1\"}" -O - "$MC_API_URL")
	
	wget_exit_code=$?
	
	if [ "$wget_exit_code" -ne 0 ]; then
		showError "Oooops, something went bad. WGET EXIT CODE (${wget_exit_code})"
	fi	

	if [ $(echo $info_link | grep '"error"') ]; then
		error_code=$($PHP_HELPERS jsonParam "$info_link" error)
		showError "ERROR: MEGACRYPTER $error_code"
	fi

	expire=$($PHP_HELPERS jsonParam "$info_link" expire)

	if [ "$expire" != "0" ]; then
	
		IFS='#' read -a array <<< "$expire"
	
		no_exp_token=${array[1]}
		
	else
		no_exp_token="$expire"
	fi
	
	if [ -z "$2" ]; then
		file_name=$(echo -ne $($PHP_HELPERS jsonParam "$info_link" name) | base64 -i 2>/dev/null)
	else
		file_name=$(echo -ne "$2" | base64 -i 2>/dev/null)
	fi
	
	path=$(echo -ne $($PHP_HELPERS jsonParam "$info_link" path) | base64 -i 2>/dev/null)
	
	mc_pass=$($PHP_HELPERS jsonParam "$info_link" pass)
	
	file_size=$($PHP_HELPERS jsonParam "$info_link" size)
	
	key=$($PHP_HELPERS jsonParam "$info_link" key)
	
	echo -ne "${file_name}@${path}@${file_size}@${mc_pass}@${key}@${no_exp_token}"
}

if [ -z "$1" ]; then
	showHelp
	exit 1
fi

if [[ "$1" =~ ^http ]]; then
	link="$1"
fi

eval set -- "$(getopt -o "l:p:k:o:s:t:" -l "list:,password:,key:,output:,speed:,no-exp-token:" -- "$@")"

while true; do
	case "$1" in
		-l|--list)     list="$2";     shift 2;;
		-p|--password) password="$2"; shift 2;;
		-o|--output)   output="$2";   shift 2;;
		-s|--speed)    speed="$2";    shift 2;;

		--) shift; break;;

		*)
			showHelp
			exit 1;;
	esac
done

if [ -z "$link" ]; then
	if [ -z "$list" ]; then
		showHelp
		showError "ERROR: MEGA link or --list parameter is required"
	elif [ ! -f "$list" ]; then
		showHelp
		showError "ERROR: MEGA list file ${list} not found"
	fi
	
	echo -ne "\nReading mc links info..."
	
	link_count=0
	
	while read line; do
	
		l=$(php -r "echo preg_replace('/^.*?(https?\:\/\/[^\/]+\/[#!0-9a-z_-]+).*$/i', '\$1', \$argv[1]);" "$line")
		
		output=$(php -r "echo trim(preg_replace('/^.*?https?\:\/\/[^\/]+\/[#!0-9a-z_-]+(.*)$/i', '\$1', \$argv[1]));" "$line")

		if [ -n "$l" ];then
			
			if ! [ $(echo -n "$l" | grep -E -o 'mega(\.co)?\.nz') ]; then
			
				md5=$(echo -n "$l" | md5sum | grep -E -o '[0-9a-f]+')
				
				if ! [ -f ".${md5}" ];then
				
					mc_link_info=$(get_mc_link_info "$l" "$output")
					
					echo -n "$mc_link_info" >> ".${md5}"
				
				fi
				
				link_count=$((link_count + 1))
			fi
		fi
	
	done < "$list"
	
	echo -ne " OK(${link_count})\n"
	
	while read line; do
	
		l=$(php -r "echo preg_replace('/^.*?(https?\:\/\/[^\/]+\/[#!0-9a-z_-]+).*$/i', '\$1', \$argv[1]);" "$line")
			
		output=$(php -r "echo trim(preg_replace('/^.*?https?\:\/\/[^\/]+\/[#!0-9a-z_-]+(.*)$/i', '\$1', \$argv[1]));" "$line")
	
		if [ -n "$l" ];then
			
			$SCRIPT "$l" --output="$output" --password="$password" --key="$key" --speed="$speed"

		fi
	
	done < "$list"

	exit 0
fi


if [ $(echo -n "$link" | grep -E -o 'mega(\.co)?\.nz') ]; then
	#MEGA.CO.NZ LINK

	file_id=$(php -r "echo preg_replace('/^.*\/#!(.+)!.*$/', '\1', \$argv[1]);" "$link")
	file_key=$(php -r "echo preg_replace('/^.*\/#!.+!(.+)$/', '\1', \$argv[1]);" "$link")
	hex_raw_key=$(echo -n $(b64_pad $file_key) | base64 -d -i 2>/dev/null | od -An -t x1 | tr -d '\n ')
	mega_req_url="${MEGA_API_URL}/cs?id=&ak="
	mega_req_json="[{\"a\":\"g\", \"p\":\"$file_id\"}]"
	
	wget_exit_code=1
	
	mega_res_json=$(wget -q --header='Content-Type: application/json' --post-data "$mega_req_json" -O - "$mega_req_url")
	
	wget_exit_code=$?
	
	if [ "$wget_exit_code" -ne 0 ]; then
		showError "Oooops, something went bad. WGET EXIT CODE (${wget_exit_code})"
	fi	

	if [ $(echo -n "$mega_res_json" | grep -E -o '\[\-[0-9]+\]') ]; then
		error_code=$(php -r "echo preg_replace('/^.*\[(.*?)\].*$/', '\$1',\$argv[1]);" "$mega_res_json")
		showError "ERROR: MEGA $error_code"
	fi

	file_size=$($PHP_HELPERS jsonParam "$mega_res_json" s)
	at=$($PHP_HELPERS jsonParam "$mega_res_json" at)
	hex_key=$(hrk2hk "$hex_raw_key")
	at_dec_json=$(echo -n $(b64_pad "$at") | $OPENSSL_AES_CBC_128_DEC -K $hex_key -iv "00000000000000000000000000000000" -nopad)

	if [ ! $(echo -n "$at_dec_json" | grep -E -o 'MEGA') ]; then
		showError "ERROR: MEGA bad link"
	fi

	if [ -z "$output" ]; then
		file_name=$($PHP_HELPERS jsonParam "$(echo -n "$at_dec_json" | grep -E -o '\{.+\}')" n)
	else
		file_name="$output"
	fi
	
	mega_req_json="[{\"a\":\"g\", \"g\":\"1\", \"p\":\"$file_id\"}]"
	
	wget_exit_code=$?
	
	mega_res_json=$(wget -q --header='Content-Type: application/json' --post-data "$mega_req_json" -O - "$mega_req_url")
	
	if [ "$wget_exit_code" -ne 0 ]; then
		showError "Oooops, something went bad. WGET EXIT CODE (${wget_exit_code})"
	fi	
	
	dl_temp_url=$($PHP_HELPERS jsonParam "$mega_res_json" g)
else
	#MEGACRYPTER LINK
	
	MC_API_URL=$(echo -n "$1" | grep -i -E -o 'https?://[^/]+')"/api"
	
	md5=$(echo -n "$link" | md5sum | grep -E -o '[0-9a-f]+')
	
	if [ -f ".${md5}" ];then
		mc_link_info=$(cat ".${md5}")
	else
		mc_link_info=$(get_mc_link_info "$link" "$output")
		echo -n "$mc_link_info" >> ".${md5}"
	fi
		
	IFS='@' read -a array <<< "$mc_link_info"
	
	file_name=$(echo -n "${array[0]}" | base64 -d -i 2>/dev/null)
	
	path=$(echo -n "${array[1]}" | base64 -d -i 2>/dev/null)
	
	file_size=${array[2]}
	
	mc_pass=${array[3]}
	
	key=${array[4]}
	
	no_exp_token=${array[5]}

	if [ "$path" != "0" ] && [ -n "$path" ]; then
	
		if [ ! -d "$path" ]; then
		
			mkdir -p "$path"
		fi
		
		file_name="${path}${file_name}"
	fi
	
	if [ "$mc_pass" != "0" ]; then
		if [ -z "$password" ]; then
			if [ $($PHP_HELPERS passwordCheck "$password" "$mc_pass") == "bad-password" ]; then
				pass=""
			fi
		fi

		if [ -z "$pass" ]; then
			read -e -p "Link is password protected. Enter password: " pass

			pass_hash=$($PHP_HELPERS passwordCheck "$pass" "$mc_pass")

			until [ "$pass_hash" != "bad-password" ]; do
				read -e -p "Wrong password! Try again: " pass
				pass_hash=$($PHP_HELPERS passwordCheck "$pass" "$mc_pass")
			done
		fi
		
		IFS='#' read -a array <<< "$pass_hash"
		
		pass_hash=${array[0]}
		
		iv=${array[1]}

		hex_raw_key=$(echo -n $(b64_pad "$key") | $OPENSSL_AES_CBC_256_DEC -K $pass_hash -iv "$iv" | od -An -t x1 | tr -d '\n ')

		if [ -z "$output" ]; then
			file_name=$(echo -n $(b64_pad "$file_name") | $OPENSSL_AES_CBC_256_DEC -K $pass_hash -iv "$iv")
		fi
	else
		hex_raw_key=$(echo -n $(b64_pad "$key") | base64 -d -i 2>/dev/null | od -An -t x1 | tr -d '\n ')
	fi
	
	hex_key=$(hrk2hk "$hex_raw_key")
	
	wget_exit_code=$?
	
	dl_link=$(wget -q --header='Content-Type: application/json' --post-data "{\"m\":\"dl\", \"link\":\"$link\", \"noexpire\":\"$no_exp_token\"}" -O - "$MC_API_URL")
	
	if [ "$wget_exit_code" -ne 0 ]; then
		showError "Oooops, something went bad. WGET EXIT CODE (${wget_exit_code})"
	fi	

	if [ $(echo $dl_link | grep '"error"') ]; then
		error_code=$($PHP_HELPERS jsonParam "$dl_link" error)

		showError "ERROR: MEGACRYPTER $error_code"
	fi

	dl_temp_url=$($PHP_HELPERS jsonParam "$dl_link" url)
	
	if [ "$mc_pass" != "0" ]; then

		iv=$(echo -n $(b64_pad $($PHP_HELPERS jsonParam "$dl_link" pass)) | base64 -d -i 2>/dev/null | od -An -t x1 | tr -d '\n ')
		
		dl_temp_url=$(echo -n $(b64_pad "$dl_temp_url") | $OPENSSL_AES_CBC_256_DEC -K $pass_hash -iv "$iv")
	fi
fi

if [ -z "$speed" ]; then
	DL_COMMAND="wget -q -O - "
else
	DL_COMMAND="wget -q --limit-rate $speed -O - "
fi

if [ "$output" == "-" ]; then
	hex_iv="${hex_raw_key:32:16}0000000000000000"
	$DL_COMMAND "$dl_temp_url" | $OPENSSL_AES_CTR_128_DEC -K $hex_key -iv $hex_iv

	exit 0
fi

if [ "$file_size" -ge 1024 ]; then
	file_size_f="~"$(($file_size/(1024*1024)))" MB"
else
	file_size_f="${file_size} bytes"
fi

if [ -f "$file_name" ]; then
	actual_size=$(wc -c "${file_name}" | cut -f 1 -d ' ')

	if [ "$actual_size" == "$file_size" ]; then
		showError "WARNING: File ${file_name} exists. Download aborted."
	fi

	echo -e "\nFile ${file_name} exists but with different size (${file_size} vs ${actual_size} bytes). Downloading [${file_size_f}] ...\n"
else
	echo -e "\nDownloading ${file_name} [${file_size_f}] ...\n"
fi

wget_exit_code=1

until [ "$wget_exit_code" -eq 0 ]; do
	if [ -f "${file_name}.temp" ]; then
		echo -e "(Resuming previous download ...)\n"

		temp_size=$(stat -c %s "${file_name}.temp")
		offset=$(($temp_size-$(($temp_size%16))))
		iv_forward=$(printf "%016x" $(($offset/16)))
		hex_iv="${hex_raw_key:32:16}$iv_forward"

		truncate -s $offset "${file_name}.temp"

		$DL_COMMAND "$dl_temp_url/$offset" | pv -s $(($file_size-$offset)) | $OPENSSL_AES_CTR_128_DEC -K $hex_key -iv $hex_iv >> "${file_name}.temp"
	else
		hex_iv="${hex_raw_key:32:16}0000000000000000"
		$DL_COMMAND "$dl_temp_url" | pv -s $file_size | $OPENSSL_AES_CTR_128_DEC -K $hex_key -iv $hex_iv > "${file_name}.temp"
	fi

	wget_exit_code=$?

	if [ "$wget_exit_code" -ne 0 ]; then
		showError "Oooops, download failed! WGET EXIT CODE (${wget_exit_code})"
	fi	
done

if [ ! -f "${file_name}.temp" ]; then
	showError "ERROR: FILE ${file_name} COULD NOT BE DOWNLOADED :(!"
fi

mv "${file_name}.temp" "${file_name}"

if [ -f ".${md5}" ];then
	rm ".${md5}"
fi

echo -e "\nFILE DOWNLOADED as ${file_name} :)!\n"

exit 0
